### ISSUE TITLE
New assets and total assets calculation

### ISSUE THREAD

**Issue by JonLister** [orbitlens/stellar-expert-explorer#108]
Under all assets tab the total assets is currently showing: 3,433
In the chart the total new assets created is closer to 10k

Is the total assets calculation filtering out any of the newly created assets?

**Comment by orbitlens** [comment]
The numbers on chart were invalid, as they were calculated as a total sum of all ever created assets and did not take in the account removed assets (with zero balance). Sorry for the long response, it took quite a lot of time to check everything and prepare a fix for archives ingestion engine. Fixed in v0.9.
