### ISSUE TITLE
Operations Paging issues

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#130]
- [x] Page size is small (20). Would be nice to have more (200)
- [ ] Current page (or time range) not mentioned anywhere in the page
- [x] Current page is not reflected in the URL
- [x] Prev should be disabled when on the first page (unclear what that does) 
- [x] Next usually goes on the right, Prev on the left

**Comment by orbitlens** [comment]
Fixed in v0.9.23

> Page size is small (20). Would be nice to have more (200)

Increased to 100 records per page. Too huge pages have poor UX and memory/CPU overhead.

> Current page (or time range) not mentioned anywhere in the page

We are using the cursor-based navigation, just like in Horizon API. Simple calculation of total records  number may take more than 30 seconds for assets with millions of operations, so "page N of T" style is a no go. Moreover, the data by nature is extremely volatile and page numbers will be irrelevant almost immediately after they arrive to the client.  
Operation timestamps are displayed in the operations table itself.
