### ISSUE TITLE
GAAZI...WN7 account fails to load

### ISSUE THREAD

**Issue by 20kdc** [orbitlens/stellar-expert-explorer#147]
Not much to say here.
At time of writing...
This will fail:
https://stellar.expert/explorer/public/account/GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7
This will succeed:
https://horizon.stellar.org/accounts/GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7/transactions?order=asc

On a side note, there's an anomaly with Stellar Laboratory that could be related:
This will fail:
https://www.stellar.org/laboratory/#explorer?resource=ledgers&endpoint=single&values=eyJsZWRnZXIiOiIzIn0%3D&network=public
This will succeed:
https://horizon.stellar.org/ledgers/3

**Comment by orbitlens** [comment]
GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7 is a ledger genesis account. It has negative balance since it created all lumens on the pubnet. Negative balance causes our API server to crash. That wasn't an issue when I checked last time (probably a few months ago), so it may be a regression bug. 
We'll fix this in the upcoming release.
Thanks for the heads up!

**Comment by 20kdc** [comment]
Checked now, it appears to load. Closing because the issue's resolved. Thanks!

**Comment by 20kdc** [comment]
Additional side note: balance history is still weird, but the account has 8 operations, and only 3 of those actually matter, so it's not a concern.
It's now basically the universal proof-of-burning account.
