### ISSUE TITLE
About the airdrop

### ISSUE THREAD

**Issue by lekantolu** [orbitlens/stellar-expert-explorer#174]
I haven't been paid and I did everything ryt
Account's name:olamilekan0811 and I will passed by
Why?
Please rectify

**Comment by jamesjoan168** [comment]
Same here, my account is jamesjoan and I haven't been paid also

**Comment by fishcharlie** [comment]
The Keybase Airdrop is over.

**Comment by jamesjoan168** [comment]
I understand but why didn't I get an airdrop, I qualified for it

**Comment by fishcharlie** [comment]
@jamesjoan168 Probably because you broke the rules, didn't read the fine print, or weren't truly qualified for it. A lot of accounts that were qualified got disqualified due to trying to circumvent the rules and creating multiple accounts. Any behavior that they detect that makes it look like you were trying to get multiple airdrops got you banned.

Anyways, no point in even asking why you didn't get it, because it won't change the fact that it's over and you will never get it.

**Comment by jamesjoan168** [comment]
I just asked a question, you responded very fine and sensible but sounded
very rude toward the last paragraph, it's very bad and certainly not a way
to respond to a customer

**Comment by fishcharlie** [comment]
@jamesjoan168 First of all, you are **NOT** my customer in this conversation. I'm not sure what gave you the impression of that. But this conversation, right now between us, is **not** a company/customer conversation or relationship.

Second, I don't like scammers. Simple as that. I don't think anyone does. The reality is you are coming onto a thread about stellar.expert, which has **NOTHING** to do with the Keybase Airdrop, and spamming it with questions that are irrelevant to the purpose of this GitHub repository. Which is just wrong.

On top of that, you obviously didn't get the Keybase Airdrop for some reason, if you claim you were qualified for it, but didn't get it, that means Keybase detected you trying to scam the system and rules, and benefit from it more than you were allowed to. Which I believe is wrong.

These messages are not intended to be rude at all. But they are intended to be firm, because I think it's rude and selfish to come onto a platform that has nothing to do about the Keybase Airdrop and complain about not receiving Lumens for free.

**Comment by fishcharlie** [comment]
@jamesjoan168 Looking through the ledger, you received almost the entire Keybase Airdrop giveaway from another Keybase user with the username of `izuu08` (https://stellar.expert/explorer/public/tx/117290278339084288#117290278339084289). After which the account proceeded to have a lot of transactions between the amounts of 353 and 355 XLM. Couldn't tell you what the purpose of that was. But it doesn't surprise me one bit that you didn't receive the Airdrop directly.

You created your GitHub account 7 hours ago. Both Keybase accounts look very similar. Both created within days of each other. Each only has 1 legit device, and 2 paper keys. Neither has a profile picture. Neither account looks like an actual legitimate person. Just important things to keep in mind when thinking about why you didn't get the Airdrop.

Anyways. In the end, you got your Lumens from `izuu08` (https://stellar.expert/explorer/public/op/117290278339084289). So really not sure what the issue is here.

**Comment by orbitlens** [comment]
StellarExpert is not affiliated with SDF or Keybase. We do not administer the airdrop and don't know why you haven't received yours.
