### ISSUE TITLE
How to query XLM Balance of Account?

### ISSUE THREAD

**Issue by gensleralexander** [orbitlens/stellar-expert-explorer#187]
Using `https://api.stellar.expert/explorer/public/account/{account}` does not include the XLM balance. How to get this?

**Comment by orbitlens** [comment]
The API endpoint you are referencing is not public. This means that it is not standardized and not intended for public use. The API contracts, endpoint URL address, and the data itself for private endpoints is a subject to change without further notice. Moreover, our firewall proactively finds and blocks bots and external API consumers based on the access pattern that use the aforementioned endpoints. The reason is that most of private endpoints extensively use server resources on our servers. Until we find a way to optimize resource consumption, those endpoints will remain non-public.

[Here](https://github.com/orbitlens/stellar-expert-explorer/blob/master/docs/api/index.md) is the list of the public StellarExpert APIs that can be used by third-party services free of charge. The data format of those APIs will not change over time.

Back to your original question, you might want to check [Stellar Horizon API reference](https://www.stellar.org/developers/horizon/reference/index.html), and specifically, [`/accounts/{account}` endpoint](https://www.stellar.org/developers/horizon/reference/endpoints/accounts-single.html). You can fetch the data you need from public Horizon server following the documentation, for example 
```
https://horizon.stellar.org/accounts/GBLKRATZODTSJNU7XTB5HY5VAAN63CPRT77UYZT2VLCNXE7F3YHSW22M
```
