### ISSUE TITLE
No received Successful transaction.

### ISSUE THREAD

**Issue by jominman** [orbitlens/stellar-expert-explorer#192]
Hi.
I´ve done my first stellar transacion 
(reference: 265b1cbafa2a8586f5ddbb0f7aa55c02420cf6312393aedf2d8c7ca1171fa98d)
and the status is: Successful but i have not received the 183 lumens in my coinbase account.
What is wrong?

Could i repeate the transaction?

I did it on may 3rd.

Thanks.

**Comment by orbitlens** [comment]
Every custodial deposit requires a valid memo. And you simply typed "XLM memo ID" instead of it. That's why your payment could not been processed automatically.

You need to contact Coinbase support team and provide transaction id (265b1cbafa2a8586f5ddbb0f7aa55c02420cf6312393aedf2d8c7ca1171fa98d) and other info required to process your deposit manually. It's impossible to change/reverse/cancel your transaction.
