### ISSUE TITLE
Memo ID epic fail

### ISSUE THREAD

**Issue by mrsixtoo520** [orbitlens/stellar-expert-explorer#206]
I am a noob and my phone screen was cracked so I mistook an 8 for a 6 when inputing my ID ..Is there nothing that can be done to remedy this? Thanks

**Comment by orbitlens** [comment]
Hello,
You should contact the destination exchange and ask them to deposit your tokens manually. Provide transaction details, and your memo id.

You can also make one more deposit (for example, 1XLM) from the same source address to exchange with a correct memo in order to prove secret key ownership. This may speed up the process.
