### ISSUE TITLE
[Testnet only] /accounts endpoint is not showing any data after 9/30

### ISSUE THREAD

**Issue by CassioMG** [orbitlens/stellar-expert-explorer#233]
I believe this is happening because Testnet updated on 9/30, so it probably broke something.

Sample transaction from "Operations Live Stream" **2020-10-02**:
https://stellar.expert/explorer/testnet/tx/410128d014f24ca394fcdf91a14d3438aa15e477a720260c8b6b561040d259b6

You can't see it in the account:
https://stellar.expert/explorer/testnet/account/GBBJCUHMBD7JINJIFPODILG6HRLZXGLHATXHO3A7MMHCFKBIBPYMLIEH?order=desc

**Comment by orbitlens** [comment]
Hey Cassio,

Yes, you are right the ingestion of the testnet data has been temporary halted due to the testnet protocol upgrade. We prepared our codebase in advance, but new transactions contained a few edge cases which broke our ingestion data processing pipeline. 

At the moment the website and all services are operational. However, you may experience some problems with new operations introduced in the protocol v14. We are still working on updating user interface to display those new operations correctly.

I'll get back to you once the new release is rolled out.

And thanks for the heads up.

**Comment by orbitlens** [comment]
Implemented text description for all new operation types. Information about pending claimable balances and sponsored reserves available on the account page.
