### ISSUE TITLE
Never received XLM to other wallet 

### ISSUE THREAD

**Issue by editorabruno** [orbitlens/stellar-expert-explorer#248]
Hi, I sent my Stellar Lumens to another wallet but never received it. I thought I filled everything out correctly and I know I pasted the right Stellar address.  

Was I supposed to write something specific in the public memo? I thought I could write whatever I wanted :-( 

Hope you can help. 

My transaction ID is: 5c2be2c7f13364817bc6e6e895a7b1a5fbb17f40cf092ee4d53ab2e02ad6088b

**Comment by orbitlens** [comment]
The funds arrived to the destination address but not to your custodial account because you entered wrong transaction memo. 
You need to contact Coinbase support, and provide a transaction id (5c2be2c7f13364817bc6e6e895a7b1a5fbb17f40cf092ee4d53ab2e02ad6088b).
They will be able to deposit your tokens manually.

**Comment by editorabruno** [comment]
Will do. Thank you for your help.
