### ISSUE TITLE
Error to change set option value

### ISSUE THREAD

**Issue by RASTecnoTI** [orbitlens/stellar-expert-explorer#356]
Hi

I am trying to change the Home Domain parameter for my issuer account and everytime finish with error 400.

I follow this guide but not worked: https://stellar.stackexchange.com/questions/2821/cant-change-low-threshold-to-0-in-set-options

My issuer account is GCRZ3AXG3LKYGWUUZHK64FEUVQ64UNEIKUCWCR5JOL336UUIIE2ZLOYG

Thank you

**Comment by orbitlens** [comment]
Sorry for the long response. We are overwhelmed with support requests at the moment.
Looks like you managed to set correct thresholds for your account because currently its status is shown as ["locked"](https://stellar.expert/explorer/public/account/GCRZ3AXG3LKYGWUUZHK64FEUVQ64UNEIKUCWCR5JOL336UUIIE2ZLOYG).
So I'm closing this.

**Comment by RASTecnoTI** [comment]
Hi
Thank you for your return. So, once the account locked is not possible change enything, not even the home domain?
Another question, is possible drop or delete these accounts (issuer and distritution) and recreate the token?
Thank you.

**Comment by orbitlens** [comment]
No, you can't do anything with it since there is no active singers available.
To recreate the token, you'll need to create a new account, and distribute new tokens to current token holders. The easiest way is to set up a DEX offer that will exchange old tokens for the new tokens at the 1:1 rate. People will be able to trade tokens using any Stellar wallet in this case.

**Comment by RASTecnoTI** [comment]
So, I need to do the procedure to create a new token, with the same name and exchange the old for the new, right?
But the older, after remove all thust, can I delete de account? I dont want have 2 tokens with the same name.

**Comment by orbitlens** [comment]
No, you cannot. The whole purpose of account locking is to prevent a token issuer from doing these things. Once the account is locked, it's impossible, for example, to dilute tokens supply or change home domain - this protects users from potentially malicious actions of token issuers.

**Comment by RASTecnoTI** [comment]
Understood.
I just need add the link of my page on home domain to complete the information about the token. In fact, I want give more information to my users.
