### ISSUE TITLE
verified on toml file

### ISSUE THREAD

**Issue by fightingmonsters1969** [orbitlens/stellar-expert-explorer#367]
i am verified i checked and it say s that my tom;l file an tokens are showing right on my website but still shows unknown status on the tokens themselves. No i did get this error code this morning does anyone know what this means ?"T_BASIC_UNESCAPED" at line 1 with value "﻿". Expected ... - did not match any documents.

my website is ohcheesy.com the token is STV for stop the violence

**Comment by orbitlens** [comment]
Hello,
First of all, a `home_domain` property of the issuing account for your token is not set to `ohcheesy.com`. That's why clients are unable to pull toml info from your site. Second, the file itself is malformed: https://stellar.sui.li/toml-check/ohcheesy.com

Please follow the [official guide](https://developers.stellar.org/docs/issuing-assets/publishing-asset-info/) to fix the issues.

**Comment by fightingmonsters1969** [comment]
Thanks

**Comment by fightingmonsters1969** [comment]
I will make sure it is fixed first thing tomorrow morning I am sorry I have
never did this before and trying to learn the blockchain and
everything associated with it

**Comment by fightingmonsters1969** [comment]
My toml file say it passes then all the sudden when i add it to the url one
it says it fails
