### ISSUE TITLE
Stellar Lumen transfer failed. 

### ISSUE THREAD

**Issue by sangreddy32** [orbitlens/stellar-expert-explorer#398]
I have transferred XML from Coinbase Pro to destination wallet address : GA6SXIZIKLJHCZI2KEOBEUUOFMM4JUPPM2UTWX6STAWT25JWIEUFIMFF , XLM Memo ID: 6191136853.

Transaction hash : https://stellar.expert/explorer/public/tx/efefa3ce6fb94e56ea22c4266a72a954a7193563a520309af212b30f027298de

I don't see my XML source Coinbase pro wallet or destination wallet. Please look into this need help on this.

**Comment by orbitlens** [comment]
Judging from the transaction result, the payment failed because you didn't have enough funds on the account balance at the moment when the transaction has been submitted. It failed, so funds shouldn't be deducted from your balance. 

If you don't see funds on you balance still, you need to contact Coinbase Pro support team.
