### ISSUE TITLE
Incorrect Pricing for BTC asset, VCBEAR.NET anchor.

### ISSUE THREAD

**Issue by mishmang** [orbitlens/stellar-expert-explorer#44]
Hello,

It appears to be showing the XRP/BTC price instead of the XLM/BTC price.

More info in the below reddit:

https://www.reddit.com/r/Stellar/comments/7xulqi/question_about_indicative_price_on_stellarexpert/

**Comment by orbitlens** [comment]
The price ticker shows the price of the last trade. Due to the low market liquidity sometimes you can see price spikes. The mentioned market (VCBear-BTC/XLM) has extremely high volatility (more than 100% from average price), so the price may swing wildly.
It's not a bug, rather a low asset liquidity issue.

**Comment by orbitlens** [comment]
Looks like there are some problems with aggregation.

**Comment by orbitlens** [comment]
Blocked by #14.
