### ISSUE TITLE
direct operation link

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#66]
Given that operation id is a unique identifier, and that some horizon resources include operation ids but not transaction hashes (specifically, trades), it would be great to have a direct link to operation. for example: 

https://stellar.expert/explorer/public/op/73730543929286657

This could be implemented as a simple redirect to the transaction page. 

Essentially: 
1. receive an http get request: https://stellar.expert/explorer/public/op/{op_id}
2. fetch operation information from: https://horizon.stellar.org/operations/{op_id}
3. use transaction hash to redirect to: https://stellar.expert/explorer/public/tx/{tx_has}#{op_id}

The redirect can be either a server side http redirect, or a soft client side redirect.

**Comment by tomerweller** [comment]
(essentially, an extension of #59)

**Comment by orbitlens** [comment]
Implemented in `0.8.5`. 

Link format: `https://stellar.expert/explorer/public/op/{operation_id}`

Since the search by transactiond_id (numeric one) is already implemented, I just retrieve a transaction id directly from the given operation id, eliminating a call to the `/operations/{operation_id}` Horizon API endpoint. And then redirect redirect to `/tx/{tx_id}#{op_id}` URL, like [`https://stellar.expert/explorer/public/tx/83010099945156608#83010099945156609`](https://stellar.expert/explorer/public/tx/83010099945156608#83010099945156609).
