### ISSUE TITLE
chart history broke for one account

### ISSUE THREAD

**Issue by dgobaud** [orbitlens/stellar-expert-explorer#75]
https://stellar.expert/explorer/public/account/GAKYXYYEOQX2HM6WCHFSIT66NIRJXPJK4VYXO4L35SDJVEGU4EXKKT5G

for MOBI shows flat line at 0 but there has been a lot of in/out

**Comment by orbitlens** [comment]
Balance history chart shows aggregated balance at the end of the day. Every time GAKY...KT5G received MOBI, it transferred (distributed?) the whole amount to other accounts immediately. So MOBI balance at the end of the day was always 0. So it's an expected behavior

I'll see what can be done with it.

Thanks for submitting the issue.

**Comment by dgobaud** [comment]
ah yes that explains it :) PS love stellar.expert!!

**Comment by orbitlens** [comment]
Fixed in v0.9
